path: dataset
train: images/train
val: images/val
batch_size: 10
augmentation:
  mosaic: 0.5
  mixup: 0.5
  degrees: 10
  translate: 0.2
  scale: 0.5
  perspective: 0.2

nc: 3
names: [glide, loose, slab]
